version: '1.1'
services:
  web:
    build: .
    ports:
      -5000:5000
    depends_on:
      - db


    db:
      image: mysql:8
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: devopsdb
      ports:
        - "3306:3306"